name: "Bug or Feature Request"
description: "Report a bug or request a new feature in the Terraform module"
title: "[Bug/Feature]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing!
        Please fill out the following information to help us resolve your issue or implement your feature request quickly.

  - type: dropdown
    id: issue_type
    attributes:
      label: "Type of Issue"
      description: "Is this a bug report or a feature request?"
      options:
        - "Bug"
        - "Feature Request"
      default: 0
    validations:
      required: true

  - type: input
    id: terraform_version
    attributes:
      label: "Terraform Version"
      description: "Please provide the version of Terraform you're using (e.g., v1.5.0)"
      placeholder: "v1.5.0"
    validations:
      required: true

  - type: input
    id: azurerm_version
    attributes:
      label: "AzureRM Provider Version"
      description: "Specify the version of the AzureRM provider used (e.g., v3.64.0)"
      placeholder: "v3.64.0"
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "Error Message"
      description: "Paste the exact error message or logs, if applicable."
      placeholder: "Error details go here..."
      render: shell

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "Steps to Reproduce"
      description: |
        Provide detailed steps to help us understand how to reproduce the issue.  
        Include relevant Terraform code snippets or `tfvars` inputs.
      placeholder: |
        1. Run `terraform init`
        2. Apply the following Terraform code...
        3. See the error...

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen instead?"

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened when you ran the code?"

  - type: textarea
    id: additional_comments
    attributes:
      label: "Additional Comments"
      description: |
        Any other context, screenshots, or logs that could help us troubleshoot or understand your request.
      placeholder: "Add any extra details here..."
